{
 "title": "Admiral",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Room", "query": "screeps.maxibra.roomSummary.*" }
  ]
 },
 "panels": [
  {
   "title": "Controller",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "range",
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.controller_progress"
    }
   ]
  },
  {
   "title": "Controller / GCL Progress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Controller" }
   ],
   "targets": [
    {
     "target": "alias(screeps.maxibra.gcl.progress, 'GCL')"
    },
    {
     "target": "alias(screeps.maxibra.roomSummary.$Room.controller_progress, 'Controller')"
    }
   ]
  },
  {
   "title": "GCL target",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 13, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "target": "screeps.maxibra.gcl.progressTotal"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(screeps.maxibra.cpu.bucket, 'Bucket')"
    },
    {
     "target": "alias(screeps.maxibra.cpu.used, 'Used')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(screeps.maxibra.memory.used, 'Mem Used')"
    }
   ]
  },
  {
   "title": "GCL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "format": "locale",
   "valueName": "range",
   "targets": [
    { "target": "screeps.maxibra.gcl.progress" }
   ]
  },
  {
   "title": "Total Creeps",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.num_creeps"
    },
    {
     "target": "screeps.maxibra.roomSummary.$Room.creep_counts"
    }
   ]
  },
  {
   "title": "Enemy Creeps",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.num_enemies"
    }
   ]
  },
  {
   "title": "Spawning",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.spawns_spawning"
    }
   ]
  },
  {
   "title": "harvest",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 6 },
   "repeat": "CreepType",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.creep_counts.harvest"
    }
   ]
  },
  {
   "title": "Energy miner",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.creep_counts.energy_miner"
    }
   ]
  },
  {
   "title": "Upgrade",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.creep_counts.upgrade"
    }
   ]
  },
  {
   "title": "Transfer",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.creep_counts.transfer"
    }
   ]
  },
  {
   "title": "mineral miner",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.creep_counts.mineral_miner"
    }
   ]
  },
  {
   "title": "defence",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.creep_counts.defence_repair"
    }
   ]
  },
  {
   "title": "Storage Energy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.storage_energy"
    }
   ]
  },
  {
   "title": "Terminal Energy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.terminal_energy"
    }
   ]
  },
  {
   "title": "Container Energy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.container_energy"
    }
   ]
  },
  {
   "title": "Link Energy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.link_energy"
    }
   ]
  },
  {
   "title": "Source Energy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.source_energy"
    }
   ]
  },
  {
   "title": "Spawn Energy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.energy_avail"
    }
   ]
  },
  {
   "title": "Tower Energy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.tower_energy"
    }
   ]
  },
  {
   "title": "Creep Energy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.creep_energy"
    }
   ]
  },
  {
   "title": "Ground Energy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.ground_resources.energy"
    }
   ]
  },
  {
   "title": "Worst Road",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(screeps.maxibra.roomSummary.$Room.structure_info.road.min_hits, 'Road minimum hits')"
    }
   ]
  },
  {
   "title": "Worst Container",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.structure_info.container.min_hits"
    }
   ]
  },
  {
   "title": "Worst Rampart",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(screeps.maxibra.roomSummary.$Room.structure_info.rampart.min_hits, 'Worst Rampart')"
    }
   ]
  },
  {
   "title": "Worst Wall",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(screeps.maxibra.roomSummary.$Room.structure_info.constructedWall.min_hits, 'Worst Wall')"
    }
   ]
  },
  {
   "title": "Controller Downgrade",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.controller_downgrade"
    }
   ]
  },
  {
   "title": "Credits",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "screeps.market.credits" }
   ]
  },
  {
   "title": "Construction Sites",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.num_construction_sites"
    }
   ]
  },
  {
   "title": "Mineral Storage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.storage_minerals"
    }
   ]
  },
  {
   "title": "Terminal Minerals",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.terminal_minerals"
    }
   ]
  },
  {
   "title": "Mineral Available",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "screeps.maxibra.roomSummary.$Room.mineral_amount"
    }
   ]
  }
 ]
}